
@startuml MESSAGE_Classes
  

' Starting classes diagram
!theme aws-orange

title MESSAGE Canada Classes

' Main model class
class model_MSG {
	' Class methods
	- __init__(): initialize class parameters
	- config_validation(): config file validator
	- map_yv_ya_lt(): MESSAGE_IX mapper of year vintage to year active (used in creating dataframes)
	- add_technology(): method to add new technologies to the model
	- add_hydrogen_shares(): method to add hydrogen shares to the model
	- process_gdp_population_data(): method to process SSP GDP and population numbers into the model
	- adjust_demands(): method to adjust demands in the scenario based on population and GDP data
	- add_population_gdp_to_scenario(): method to add processed population and GDP data to the scenario
	- update_historical_activity(): method to update the historical activity parameter in the scenario
	- balance_import_export(): method to balance import and export for each province and year in the scenario
	- sum_demand(): subfunction to balance_import_export() to sum up the demands
	- balance_energy(): subfunction to balance_import_export() to balance the energy production, import, and export for a specific energy type
	- generate_report():MESSAGE_IX function to generate a CSV report of the scenario
	- clone_scenario(): MESSAGE_IX function to create a copy of an existing instance of this class (with same inputs and existing parameters)
	- setup_scenario(): model instantiation method. creates the MESSAGE_IX Scenario object and solves it if possible
	
	------------------------------------

	' Class parameters

	~ scenario: scenario name 
	~ sample_config: working toml configuration 
	~ scenario_path: parent path to scenario (i.e scenario folder)
	~ config_path: path to configuration file from scenario
	~ config: scenario settings (toml file)
	~ modelName: model name for outputs and plotting (used in GAMS)
	~ scenarioName: name of scenario for outputs and plotting
	~ platform_name: IXMP platform
	~ version: MESSAGE version (used in GAMS)
	~ annotation: comments on scenario
	~ process_historical: flag for processing historical data
	~ add_hydrogen_shares_f: flag for hydrogen shares
	~ add_obps_baseline: flag for baseline OBPS standard
	~ add_obps_netzero: flag for OBPS in netzero scenario
	~ use_reporter: flag for MESSAGE_IX reporting
	~ solve: flag to call solver (used in GAMS)
	~ to_excel: flag to convert results to Excel files
	~ add_techs: flag to add new technologies to the model
	~ mp
}


' Plotter class
class plotter_MSG {
	- __init__(): initialize class parameters
    - group(): method to group dataframes over an index and a column. Returns a dataframe
    - multiply_df(): method to merge two dattaframes by multiplying their column values. Returns a dataframe
    - attach_history(): method to calculate the historical data being attached to the model values in the plots
    - plotdf(): method for calculating final dataframe that will be plotted
    - plotdf_com(): method for aggregating the commodities by level in a single dataframe
    - mappings(): method to apply the mapping (names, commodity units, etc) to plots
    - plotdf_ind(): method to aggregate dataframes for industry and energy sector
    - add_history(): method to add historical data to the model values for the plots
    - model_output(): method to create compact output report for the model
    - com_order(): method to reorganze the columns of a dataframe according to the self.order parameter
    - plotter(): method that plots all the required graophs from the scenario's solution 
    
	------------------------------------

	~ scenario: MESSAGE scenario object
	~ color_map: dictionary of fuels to their colors for plots
	~ dict_plot: dictionary of plot titles to their kind and unit
	~ crudes: list ofcommodities of the "crude" type
	~ gases: list of commodities of the "gas" type
    ~ min_val: minimum value to show in plots
    ~ min_abs: minimum absolute value to show in plots
    ~ renaming: dictionary of names for labels on plots from internal MESSAGE_IX names
	~ unitc: unit conversion from GWa to PJ
    ~ unit_el: unit conversion from GWa to TWh 
    ~ unit_cap: unit conversion from GW to MW
	~ unitname: PJ (peta-joules)
	~ unitname_el: TWh (Terawatt-hour)
	~ unitname_cap: MW (Megawatt)
    ~ fntsz: font size to be used in plots
    ~ fntcol: font color to be used in plots 
	~ lw: plot line width
    ~ tickwdt: plot tick width
	~ ticksz: plot tick size
	~ kind: type of plot being produced by the class 
	~ order: ordering of commodities on plots
	~ abbrev_prov: dictionary of province names and their respective official abbreviation
    
}

@enduml
